require: rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Max: 120
  IgnoreCopDirectives: true

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/**/*_spec.rb

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Style/LambdaCall:
  EnforcedStyle: braces
