language: ruby
rvm:
  - 2.3.3
  - 2.4.0
before_install:
  - gem update --remote bundler
  - gem update --system
script:
  - bundle exec rvm info
  - bundle exec rubocop -V
  - bundle exec rspec --version
  - RUBOCOP_CONFIG="travis-ci/.rubocop-${RUBY_VERSION}.yml"
  - if [[ ! -f "$RUBOCOP_CONFIG" ]]; then RUBOCOP_CONFIG=.rubocop.yml; fi
  - rubocop -c $RUBOCOP_CONFIG
  - bundle exec rspec
